### ISSUE TITLE
How to start parrot vnc

### ISSUE THREAD

**Issue by dr1408** [AryanVBW/LinuxDroid#8]
Sir how to start vnc in parrot i use your linuxdroid to install GUI version of parrot

**Comment by dr1408** [comment]
And how to uninstall parrot completely and return the default basharc .. all these steps are not mentioned

**Comment by AryanVBW** [comment]
**© LinuxDroid** 
To install and start VNC server on Parrot OS, you can use the following steps:

1. **Install a VNC Server:**
   Open a terminal and run the following command to install a VNC server. For example, you can use `tightvncserver`:

   ```bash
   sudo apt-get install tightvncserver
   ```

2. **Start the VNC Server:**
   After the installation is complete, run the following command to start the VNC server:

   ```bash
   tightvncserver
   ```

   During the first run, you'll be prompted to set up a password for VNC access. Enter a strong password as instructed.

3. **Stop the VNC Server (Optional):**
   If you ever need to stop the VNC server, you can use the following command:

   ```bash
   tightvncserver -kill :1
   ```

   Replace `:1` with the display number if you are using a different one.

4. **Configure Autostart (Optional):**
   To configure the VNC server to start automatically when you boot your system, you might need to add a command to the startup scripts. This can be done by modifying the appropriate configuration file, such as `~/.config/autostart/tightvnc.desktop` or using other methods depending on your desktop environment.

**Comment by dr1408** [comment]
Bash : sudo command not found 

also pkg command not found

how to fix ?

**Comment by dr1408** [comment]
Your comaands doesn't work

**Comment by dr1408** [comment]
I delete everything thank you sir
