### ISSUE TITLE
Unable to install Ubuntu22 on termux

### ISSUE THREAD

**Issue by santoshdkolur** [AryanVBW/LinuxDroid#9]
I have run the code : 
`pkg update -y && pkg install wget   curl proot tar -y && wget https://github.com/AryanVBW/LinuxDroid/blob/L2/Scripts/InstallScript/Cli/ubuntu22.sh -O ubuntu22.sh && chmod +x ubuntu22.sh && bash ubuntu22.sh`

which always ends up throwing the error : 

`ls: cannot access 'ubuntu22-binds': No such file or directory
ubuntu22.sh: line 1: payload:allShortcutsEnabled:false: command not found`

**Comment by AryanVBW** [comment]
Apologies for any inconvenience caused. Please utilize the following updated commands instead of the previous ones:

```
pkg update -y && pkg upgrade -y
termux-setup-storage
pkg install wget -y && pkg install figlet -y 
wget https://github.com/AryanVBW/LinuxDroid/releases/download/scripts/LinuxDroidmenu.sh && chmod +x LinuxDroidmenu.sh
wget https://github.com/AryanVBW/LinuxDroid/releases/download/A1/default.bashrc && chmod +x default.bashrc
rm -rf .bashrc && cp default.bashrc .bashrc
wget https://github.com/AryanVBW/LinuxDroid/releases/download/scripts/LinuxDroid.sh && chmod +x LinuxDroid.sh && bash LinuxDroid.sh


```

Thank you for your understanding.

**Comment by santoshdkolur** [comment]
Thank you! I am able to get it working using the above method.

**Comment by AryanVBW** [comment]
Welcome 🤗 bro
